### PR TITLE
Contactform branch

### PR DESCRIPTION
**Pull request by luisrpavanelli**
project requirements

In that section, I built for this milestone:

- the contact form: Form
- and the footer (if present in the design)

I made sure that:
The Name field accepts up to 30 characters.
The Email field only accepts emails.
The message field accepts up to 500 characters.
All fields have placeholder text.
All fields have the correct type.
A user cannot submit the form if one or more fields are empty.
Collect data using the Formspree service.
To lay out the elements on the page, you must use Flexbox.
- No need to implement any functionality that requires JavaScript.
- Keep the design as much as possible (e.g. font, colors, images, text, margins) using Figma's templates.
Implemented the button interactions (activate, hover, etc.).
The site must be responsive following these breakpoints:
The minimum mobile screen size must be 375px
The minimum desktop screen size must be 768px
I've used responsive values in your CSS rules like percentages (i.e. width: 80%) instead of pixels.

Remind me about the big picture of this project.

Mode of work and submission
I have implemented the above requirements in all repositories in your pair programming group.
We made and worked together with commits to guarantee joint participation in the project.

### CODE REVIEW

**Review by amon-cofie — CHANGES_REQUESTED** [review]
Hi @luisrpavanelli and @najibullahjafari , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 💪 



## Highlights

🚀 You have a descriptive pull request summary
🚀 You used GitHub flow properly
🚀 You have no linter errors
🚀 You have done great work on the styling 💪 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luisrpavanelli** [comment]
I made and fixed the optional suggestion prompts.

**Review by stanleySimeon — APPROVED** [review]
# Hi @luisrpavanelli

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Status: Approved 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by taldr27 — COMMENTED** [review]
# Status: Invalidated 🔴
Hi @luisrpavanelli, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an already approved project. I just wanted to remind you that for each milestone, please **create separate feature branches and pull requests**. This helps keep everything organized and ensures that each milestone is properly reviewed and approved. Keep up the good work!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready. 🙏

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit. gif_

**Pull request merged**
