### PR TITLE
Portfolio: finish mobile version

### PR DESCRIPTION
**Pull request by luisrpavanelli**
In this PR I worked with these Project requirements:

I created the middle section of the mobile site.

We've included a screenshot of Template 1 below for reference, but you should stick to the template you choose. These sections of the mobile site should include:

- "Works" section: toolbar

- "About me" section: About me

- Content of the "About Me" section is in line with Flexbox.

To lay out the elements in the "Works" section I created CSS Grid and Flexbox combined, I used the CSS Grid in the main container that holds all the cards and I used Flexbox to create an individual card.

- I used ul and li for categories in the "Work" section. Html, CSS, and JavaScript.

- I used ul and li for categories in the "About Me" section. Languages, Frameworks, and Skills are items on the list.

I tried to keep the design as much as possible (eg font, colors, images, text, margins) using Figma's templates.

Implemented the button interactions (activate, hover, etc.).

The site is responsive following these breakpoints:

- The minimum size of the mobile screen must be 375px
- Minimum desktop screen size is 768px
I used responsive values in your CSS rules like percentages.

### CODE REVIEW

**Review by MaganaAsiati — CHANGES_REQUESTED** [review]
# STATUS: Required Changes ♻️♻️♻️ 

Hi @luisrpavanelli 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

AlonzoLeroneThisCloseGIF

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️


- Kindly make sure that the list of icons uses a ul tag to group them and li per icon; each icon has a link (a tag) also on all pages use the appropriate color the use green color instead of blue as shown in the figma design. your design must stick as much as possible to the figma design :+1: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by MaganaAsiati** [comment]
Fix linters

**Comment by luisrpavanelli** [comment]
corrected and modified as requested in the suggestion

**Comment by luisrpavanelli** [comment]
It's done, hank you so much!

**Review by Efiamotu-1 — APPROVED** [review]
Hi @luisrpavanelli , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

giphy


## Highlights :dart: 
* Correct GitHub flow or Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR Title & summary :heavy_check_mark: 
* 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [@Efiamotu-1](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[Habeeb Efiamotu Musa](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [@EFYAMOTU](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [Habeeb Efiamotu Musa](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by stanleySimeon — COMMENTED** [review]
# Hi @luisrpavanelli 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Status: Approved 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
